# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: author.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='author.proto',
  package='author',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x61uthor.proto\x12\x06\x61uthor\x1a\x1bgoogle/protobuf/empty.proto\";\n\x06\x41uthor\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\"\x13\n\x11\x41uthorListRequest\"#\n\x15\x41uthorRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x93\x02\n\x10\x41uthorController\x12\x35\n\x04List\x12\x19.author.AuthorListRequest\x1a\x0e.author.Author\"\x00\x30\x01\x12*\n\x06\x43reate\x12\x0e.author.Author\x1a\x0e.author.Author\"\x00\x12;\n\x08Retrieve\x12\x1d.author.AuthorRetrieveRequest\x1a\x0e.author.Author\"\x00\x12*\n\x06Update\x12\x0e.author.Author\x1a\x0e.author.Author\"\x00\x12\x33\n\x07\x44\x65stroy\x12\x0e.author.Author\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_AUTHOR = _descriptor.Descriptor(
  name='Author',
  full_name='author.Author',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='author.Author.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='author.Author.last_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='author.Author.first_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=112,
)


_AUTHORLISTREQUEST = _descriptor.Descriptor(
  name='AuthorListRequest',
  full_name='author.AuthorListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=133,
)


_AUTHORRETRIEVEREQUEST = _descriptor.Descriptor(
  name='AuthorRetrieveRequest',
  full_name='author.AuthorRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='author.AuthorRetrieveRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=170,
)

DESCRIPTOR.message_types_by_name['Author'] = _AUTHOR
DESCRIPTOR.message_types_by_name['AuthorListRequest'] = _AUTHORLISTREQUEST
DESCRIPTOR.message_types_by_name['AuthorRetrieveRequest'] = _AUTHORRETRIEVEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Author = _reflection.GeneratedProtocolMessageType('Author', (_message.Message,), {
  'DESCRIPTOR' : _AUTHOR,
  '__module__' : 'author_pb2'
  # @@protoc_insertion_point(class_scope:author.Author)
  })
_sym_db.RegisterMessage(Author)

AuthorListRequest = _reflection.GeneratedProtocolMessageType('AuthorListRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUTHORLISTREQUEST,
  '__module__' : 'author_pb2'
  # @@protoc_insertion_point(class_scope:author.AuthorListRequest)
  })
_sym_db.RegisterMessage(AuthorListRequest)

AuthorRetrieveRequest = _reflection.GeneratedProtocolMessageType('AuthorRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUTHORRETRIEVEREQUEST,
  '__module__' : 'author_pb2'
  # @@protoc_insertion_point(class_scope:author.AuthorRetrieveRequest)
  })
_sym_db.RegisterMessage(AuthorRetrieveRequest)



_AUTHORCONTROLLER = _descriptor.ServiceDescriptor(
  name='AuthorController',
  full_name='author.AuthorController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=173,
  serialized_end=448,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='author.AuthorController.List',
    index=0,
    containing_service=None,
    input_type=_AUTHORLISTREQUEST,
    output_type=_AUTHOR,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='author.AuthorController.Create',
    index=1,
    containing_service=None,
    input_type=_AUTHOR,
    output_type=_AUTHOR,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Retrieve',
    full_name='author.AuthorController.Retrieve',
    index=2,
    containing_service=None,
    input_type=_AUTHORRETRIEVEREQUEST,
    output_type=_AUTHOR,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='author.AuthorController.Update',
    index=3,
    containing_service=None,
    input_type=_AUTHOR,
    output_type=_AUTHOR,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Destroy',
    full_name='author.AuthorController.Destroy',
    index=4,
    containing_service=None,
    input_type=_AUTHOR,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTHORCONTROLLER)

DESCRIPTOR.services_by_name['AuthorController'] = _AUTHORCONTROLLER

# @@protoc_insertion_point(module_scope)
