# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: category.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='category.proto',
  package='category',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x63\x61tegory.proto\x12\x08\x63\x61tegory\x1a\x1bgoogle/protobuf/empty.proto\"$\n\x08\x43\x61tegory\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x15\n\x13\x43\x61tegoryListRequest\"%\n\x17\x43\x61tegoryRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xb9\x02\n\x12\x43\x61tegoryController\x12=\n\x04List\x12\x1d.category.CategoryListRequest\x1a\x12.category.Category\"\x00\x30\x01\x12\x32\n\x06\x43reate\x12\x12.category.Category\x1a\x12.category.Category\"\x00\x12\x43\n\x08Retrieve\x12!.category.CategoryRetrieveRequest\x1a\x12.category.Category\"\x00\x12\x32\n\x06Update\x12\x12.category.Category\x1a\x12.category.Category\"\x00\x12\x37\n\x07\x44\x65stroy\x12\x12.category.Category\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_CATEGORY = _descriptor.Descriptor(
  name='Category',
  full_name='category.Category',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='category.Category.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='category.Category.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=93,
)


_CATEGORYLISTREQUEST = _descriptor.Descriptor(
  name='CategoryListRequest',
  full_name='category.CategoryListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=116,
)


_CATEGORYRETRIEVEREQUEST = _descriptor.Descriptor(
  name='CategoryRetrieveRequest',
  full_name='category.CategoryRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='category.CategoryRetrieveRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['Category'] = _CATEGORY
DESCRIPTOR.message_types_by_name['CategoryListRequest'] = _CATEGORYLISTREQUEST
DESCRIPTOR.message_types_by_name['CategoryRetrieveRequest'] = _CATEGORYRETRIEVEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Category = _reflection.GeneratedProtocolMessageType('Category', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORY,
  '__module__' : 'category_pb2'
  # @@protoc_insertion_point(class_scope:category.Category)
  })
_sym_db.RegisterMessage(Category)

CategoryListRequest = _reflection.GeneratedProtocolMessageType('CategoryListRequest', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORYLISTREQUEST,
  '__module__' : 'category_pb2'
  # @@protoc_insertion_point(class_scope:category.CategoryListRequest)
  })
_sym_db.RegisterMessage(CategoryListRequest)

CategoryRetrieveRequest = _reflection.GeneratedProtocolMessageType('CategoryRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORYRETRIEVEREQUEST,
  '__module__' : 'category_pb2'
  # @@protoc_insertion_point(class_scope:category.CategoryRetrieveRequest)
  })
_sym_db.RegisterMessage(CategoryRetrieveRequest)



_CATEGORYCONTROLLER = _descriptor.ServiceDescriptor(
  name='CategoryController',
  full_name='category.CategoryController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=158,
  serialized_end=471,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='category.CategoryController.List',
    index=0,
    containing_service=None,
    input_type=_CATEGORYLISTREQUEST,
    output_type=_CATEGORY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='category.CategoryController.Create',
    index=1,
    containing_service=None,
    input_type=_CATEGORY,
    output_type=_CATEGORY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Retrieve',
    full_name='category.CategoryController.Retrieve',
    index=2,
    containing_service=None,
    input_type=_CATEGORYRETRIEVEREQUEST,
    output_type=_CATEGORY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='category.CategoryController.Update',
    index=3,
    containing_service=None,
    input_type=_CATEGORY,
    output_type=_CATEGORY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Destroy',
    full_name='category.CategoryController.Destroy',
    index=4,
    containing_service=None,
    input_type=_CATEGORY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CATEGORYCONTROLLER)

DESCRIPTOR.services_by_name['CategoryController'] = _CATEGORYCONTROLLER

# @@protoc_insertion_point(module_scope)
