# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: publisher.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='publisher.proto',
  package='publisher',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fpublisher.proto\x12\tpublisher\x1a\x1bgoogle/protobuf/empty.proto\"%\n\tPublisher\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x16\n\x14PublisherListRequest\"&\n\x18PublisherRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xcc\x02\n\x13PublisherController\x12\x41\n\x04List\x12\x1f.publisher.PublisherListRequest\x1a\x14.publisher.Publisher\"\x00\x30\x01\x12\x36\n\x06\x43reate\x12\x14.publisher.Publisher\x1a\x14.publisher.Publisher\"\x00\x12G\n\x08Retrieve\x12#.publisher.PublisherRetrieveRequest\x1a\x14.publisher.Publisher\"\x00\x12\x36\n\x06Update\x12\x14.publisher.Publisher\x1a\x14.publisher.Publisher\"\x00\x12\x39\n\x07\x44\x65stroy\x12\x14.publisher.Publisher\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_PUBLISHER = _descriptor.Descriptor(
  name='Publisher',
  full_name='publisher.Publisher',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='publisher.Publisher.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='publisher.Publisher.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=96,
)


_PUBLISHERLISTREQUEST = _descriptor.Descriptor(
  name='PublisherListRequest',
  full_name='publisher.PublisherListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=120,
)


_PUBLISHERRETRIEVEREQUEST = _descriptor.Descriptor(
  name='PublisherRetrieveRequest',
  full_name='publisher.PublisherRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='publisher.PublisherRetrieveRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=160,
)

DESCRIPTOR.message_types_by_name['Publisher'] = _PUBLISHER
DESCRIPTOR.message_types_by_name['PublisherListRequest'] = _PUBLISHERLISTREQUEST
DESCRIPTOR.message_types_by_name['PublisherRetrieveRequest'] = _PUBLISHERRETRIEVEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Publisher = _reflection.GeneratedProtocolMessageType('Publisher', (_message.Message,), {
  'DESCRIPTOR' : _PUBLISHER,
  '__module__' : 'publisher_pb2'
  # @@protoc_insertion_point(class_scope:publisher.Publisher)
  })
_sym_db.RegisterMessage(Publisher)

PublisherListRequest = _reflection.GeneratedProtocolMessageType('PublisherListRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUBLISHERLISTREQUEST,
  '__module__' : 'publisher_pb2'
  # @@protoc_insertion_point(class_scope:publisher.PublisherListRequest)
  })
_sym_db.RegisterMessage(PublisherListRequest)

PublisherRetrieveRequest = _reflection.GeneratedProtocolMessageType('PublisherRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUBLISHERRETRIEVEREQUEST,
  '__module__' : 'publisher_pb2'
  # @@protoc_insertion_point(class_scope:publisher.PublisherRetrieveRequest)
  })
_sym_db.RegisterMessage(PublisherRetrieveRequest)



_PUBLISHERCONTROLLER = _descriptor.ServiceDescriptor(
  name='PublisherController',
  full_name='publisher.PublisherController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=163,
  serialized_end=495,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='publisher.PublisherController.List',
    index=0,
    containing_service=None,
    input_type=_PUBLISHERLISTREQUEST,
    output_type=_PUBLISHER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='publisher.PublisherController.Create',
    index=1,
    containing_service=None,
    input_type=_PUBLISHER,
    output_type=_PUBLISHER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Retrieve',
    full_name='publisher.PublisherController.Retrieve',
    index=2,
    containing_service=None,
    input_type=_PUBLISHERRETRIEVEREQUEST,
    output_type=_PUBLISHER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='publisher.PublisherController.Update',
    index=3,
    containing_service=None,
    input_type=_PUBLISHER,
    output_type=_PUBLISHER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Destroy',
    full_name='publisher.PublisherController.Destroy',
    index=4,
    containing_service=None,
    input_type=_PUBLISHER,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PUBLISHERCONTROLLER)

DESCRIPTOR.services_by_name['PublisherController'] = _PUBLISHERCONTROLLER

# @@protoc_insertion_point(module_scope)
